/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package exo2;

import static exo1.Etat.INIT;
import static exo1.Etat.MARCHE;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author 21206989
 */
public class TimerAvance extends javax.swing.JFrame {

    private Etat etat;
    private Integer nbTic, compteur;
    private Timer tAvance;

    /**
     * Creates new form TimerAvance
     */
    public TimerAvance() {
        initComponents();
        etat = Etat.INIT;
        nbTic = 0;
        initCompteur();
        afficherCompteur();
        
        // Initialisation du timer qui avancera le compteur
        tAvance = new Timer(1000, null);

        tAvance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timerAvanceActionPerfomed(evt);
            }
        });

        activationInit();
    }

    private void incrementerCompteur() {
        compteur++;
    }

    private void initCompteur() {
        compteur = 0;
    }

    private void afficherCompteur() {
        jText.setText(compteur.toString());
    }

    private void afficherPouf() {
        jText.setText("POUF");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jStart = new javax.swing.JButton();
        jStop = new javax.swing.JButton();
        jText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jStart.setText("Start");
        jStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStartActionPerformed(evt);
            }
        });

        jStop.setText("Stop");
        jStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jStop)
                        .addGap(72, 72, 72)
                        .addComponent(jStart)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jText, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jStart)
                    .addComponent(jStop))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStopActionPerformed
        switch (etat) {
            case INIT:
                throw new RuntimeException("Etat interdit");
            case MARCHE:
                etat = Etat.INIT;
                nbTic = 0;
                afficherPouf();
                activationInit();
                break;
        }
    }//GEN-LAST:event_jStopActionPerformed

    private void jStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStartActionPerformed
        switch (etat) {
            case INIT:
                etat = Etat.MARCHE;
                nbTic = 0;
                initCompteur();
                afficherCompteur();
                activationMarche();
                break;
            case MARCHE:
                throw new RuntimeException("Etat interdit");
        }
    }//GEN-LAST:event_jStartActionPerformed

    private void timerAvanceActionPerfomed(java.awt.event.ActionEvent evt) {
        switch (etat) {
            case INIT:
                throw new RuntimeException("Etat interdit");
            case MARCHE:
                if (nbTic < 15) {
                    etat = Etat.MARCHE;
                    nbTic++;
                    incrementerCompteur();
                    afficherCompteur();
                    activationMarche();
                } else {
                    etat = Etat.INIT;
                    nbTic = 0;
                    afficherCompteur();
                    activationInit();
                }
                break;
        }
    }

    private void activationInit() {
        jStart.setEnabled(true);
        jStop.setEnabled(false);
        tAvance.stop();
    }

    private void activationMarche() {
        jStart.setEnabled(false);
        jStop.setEnabled(true);
        tAvance.start();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimerAvance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimerAvance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimerAvance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimerAvance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TimerAvance().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jStart;
    private javax.swing.JButton jStop;
    private javax.swing.JLabel jText;
    // End of variables declaration//GEN-END:variables
}
