/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package exo1;

/**
 *
 * @author 21206989
 */
public class AvanceClique extends javax.swing.JFrame {

    private Etat etat;
    private Integer nbTic, compteur;

    /**
     * Creates new form AvanceClique
     */
    public AvanceClique() {
        initComponents();
        etat = Etat.INIT;
        nbTic = 0;
        initCompteur();
        afficherCompteur();
        activationInit();
    }

    private void incrementerCompteur() {
        compteur++;
    }

    private void initCompteur() {
        compteur = 0;
    }

    private void afficherCompteur() {
        jText.setText(compteur.toString());
    }

    private void afficherPouf() {
        jText.setText("POUF");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jStart = new javax.swing.JButton();
        jTic = new javax.swing.JButton();
        jStop = new javax.swing.JButton();
        jText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jStart.setText("Start");
        jStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStartActionPerformed(evt);
            }
        });

        jTic.setText("Tic");
        jTic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTicActionPerformed(evt);
            }
        });

        jStop.setText("Stop");
        jStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jStop)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jStart)
                        .addGap(43, 43, 43)
                        .addComponent(jTic))
                    .addComponent(jText, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jStart)
                    .addComponent(jTic)
                    .addComponent(jStop))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStopActionPerformed
        switch (etat) {
            case INIT:
                throw new RuntimeException("Etat interdit");
            case MARCHE:
                etat = Etat.INIT;
                nbTic = 0;
                afficherPouf();
                activationInit();
                break;
        }
    }//GEN-LAST:event_jStopActionPerformed

    private void jStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStartActionPerformed
        switch (etat) {
            case INIT:
                etat = Etat.MARCHE;
                nbTic = 0;
                initCompteur();
                afficherCompteur();
                activationMarche();
                break;
            case MARCHE:
                throw new RuntimeException("Etat interdit");
        }
    }//GEN-LAST:event_jStartActionPerformed

    private void jTicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTicActionPerformed
        switch (etat) {
            case INIT:
                throw new RuntimeException("Etat interdit");
            case MARCHE:
                if (nbTic < 15) {
                    etat = Etat.MARCHE;
                    nbTic++;
                    incrementerCompteur();
                    afficherCompteur();
                    activationMarche();
                } else {
                    etat = Etat.INIT;
                    nbTic = 0;
                    afficherCompteur();
                    activationInit();
                }
                break;
        }
    }//GEN-LAST:event_jTicActionPerformed

    private void activationInit() {
        jStart.setEnabled(true);
        jStop.setEnabled(false);
        jTic.setEnabled(false);
    }

    private void activationMarche() {
        jStart.setEnabled(false);
        jStop.setEnabled(true);
        jTic.setEnabled(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;










                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AvanceClique.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AvanceClique.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AvanceClique.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AvanceClique.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AvanceClique().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jStart;
    private javax.swing.JButton jStop;
    private javax.swing.JLabel jText;
    private javax.swing.JButton jTic;
    // End of variables declaration//GEN-END:variables
}
