/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exo2;

import javax.swing.JTextArea;

/**
 *
 * @author Hugues
 */
public class Zoom extends javax.swing.JFrame {

    private Etat etat;
    private ModeleText mText;
    private ModeleZoom mZoom;

    /**
     * Creates new form Zoom
     */
    public Zoom() {
        initComponents();
        mText = new ModeleText(vueText);
        mZoom = new ModeleZoom(vueText);

        etat = Etat.ZOOM;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        j100 = new javax.swing.JButton();
        j75 = new javax.swing.JButton();
        j125 = new javax.swing.JButton();
        j150 = new javax.swing.JButton();
        j175 = new javax.swing.JButton();
        j200 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        vueText = new exo2.VueTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        j100.setText("100%");
        j100.setPreferredSize(new java.awt.Dimension(70, 25));
        j100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j100ActionPerformed(evt);
            }
        });

        j75.setText("75%");
        j75.setPreferredSize(new java.awt.Dimension(70, 25));
        j75.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j75ActionPerformed(evt);
            }
        });

        j125.setText("125%");
        j125.setPreferredSize(new java.awt.Dimension(70, 25));
        j125.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j125ActionPerformed(evt);
            }
        });

        j150.setText("150%");
        j150.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j150ActionPerformed(evt);
            }
        });

        j175.setText("175%");
        j175.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j175ActionPerformed(evt);
            }
        });

        j200.setText("200%");
        j200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j200ActionPerformed(evt);
            }
        });

        vueText.setColumns(20);
        vueText.setRows(5);
        vueText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFocusGained(evt);
            }
        });
        vueText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(vueText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(j75, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j100, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j125, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j150, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j175, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j200, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j100, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j75, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j125, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j150, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j175, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j200, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j125ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j125ActionPerformed
        switch (etat) {
            case ZOOM:
                etat = Etat.ZOOM;
                mZoom.setValue(125);
                mZoom.notifier();
                activationZoom();
            case EDITTEXT:
                etat = Etat.ZOOM;
                mZoom.setValue(125);
                mZoom.notifier();
                activationZoom();
        }
    }//GEN-LAST:event_j125ActionPerformed

    private void j150ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j150ActionPerformed
        switch (etat) {
            case ZOOM:
                etat = Etat.ZOOM;
                mZoom.setValue(150);
                mZoom.notifier();
                activationZoom();
            case EDITTEXT:
                etat = Etat.ZOOM;
                mZoom.setValue(150);
                mZoom.notifier();
                activationZoom();
        }
    }//GEN-LAST:event_j150ActionPerformed

    private void j200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j200ActionPerformed
        switch (etat) {
            case ZOOM:
                etat = Etat.ZOOM;
                mZoom.setValue(200);
                mZoom.notifier();
                activationZoom();
            case EDITTEXT:
                etat = Etat.ZOOM;
                mZoom.setValue(200);
                mZoom.notifier();
                activationZoom();
        }
    }//GEN-LAST:event_j200ActionPerformed

    private void j175ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j175ActionPerformed
        switch (etat) {
            case ZOOM:
                etat = Etat.ZOOM;
                mZoom.setValue(175);
                mZoom.notifier();
                activationZoom();
            case EDITTEXT:
                etat = Etat.ZOOM;
                mZoom.setValue(175);
                mZoom.notifier();
                activationZoom();
        }
    }//GEN-LAST:event_j175ActionPerformed

    private void j75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j75ActionPerformed
        switch (etat) {
            case ZOOM:
                etat = Etat.ZOOM;
                mZoom.setValue(75);
                mZoom.notifier();
                activationZoom();
            case EDITTEXT:
                etat = Etat.ZOOM;
                mZoom.setValue(75);
                mZoom.notifier();
                activationZoom();
        }
    }//GEN-LAST:event_j75ActionPerformed

    private void j100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j100ActionPerformed
        switch (etat) {
            case ZOOM:
                etat = Etat.ZOOM;
                mZoom.setValue(100);
                mZoom.notifier();
                activationZoom();
            case EDITTEXT:
                etat = Etat.ZOOM;
                mZoom.setValue(100);
                mZoom.notifier();
                activationZoom();
        }
    }//GEN-LAST:event_j100ActionPerformed

    private void textFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFocusGained
        switch (etat) {
            case ZOOM:
                etat = Etat.EDITTEXT;
                activationEdittext();
            case EDITTEXT:
                etat = Etat.ZOOM;
                activationZoom();
        }
    }//GEN-LAST:event_textFocusGained

    private void textKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textKeyPressed

    }//GEN-LAST:event_textKeyPressed

    private void activationZoom() {
        j75.setEnabled(true);
        j100.setEnabled(true);
        j125.setEnabled(true);
        j150.setEnabled(true);
        j175.setEnabled(true);
        j200.setEnabled(true);
        //vueText.setFocusable(false);
    }

    private void activationEdittext() {
        j75.setEnabled(true);
        j100.setEnabled(true);
        j125.setEnabled(true);
        j150.setEnabled(true);
        j175.setEnabled(true);
        j200.setEnabled(true);
        //vueText.setFocusable(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Zoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Zoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Zoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Zoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Zoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton j100;
    private javax.swing.JButton j125;
    private javax.swing.JButton j150;
    private javax.swing.JButton j175;
    private javax.swing.JButton j200;
    private javax.swing.JButton j75;
    private javax.swing.JScrollPane jScrollPane1;
    private exo2.VueTextArea vueText;
    // End of variables declaration//GEN-END:variables
}
