/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exo1;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.JPanel;

/**
 *
 * @author Hugues
 */
public class Cercle extends javax.swing.JPanel {

    // Boolean permettant de savoir si la couleur est active ou non
    private Boolean allumer;
    private Color color;

    /**
     * Creates new form Cercle
     */
    public Cercle(Color color) {
        initComponents();
        allumer = false;
        this.color = color;
        this.setPreferredSize(new Dimension(50,50));
    }

    public void setAllumer(Boolean allumer) {
        this.allumer = allumer;
    }

    public class Panneau extends JPanel {

        @Override
        public void paintComponent(Graphics g) {
            if (allumer) {
                g.setColor(color);
                g.fillOval(0, 0, this.getWidth(), this.getHeight());
            } else {

                g.setColor(Color.BLACK);
                g.fillOval(0, 0, this.getWidth(), this.getHeight());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
